# Generated by Django 3.2.7 on 2021-09-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("name", models.CharField(default="Euro", max_length=48, null=True)),
                ("symbol", models.CharField(max_length=4, null=True)),
                (
                    "code",
                    models.CharField(
                        default="EUR", max_length=3, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name": "currency",
                "verbose_name_plural": "currencies",
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="DSR",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("path", models.CharField(default="/path/to/dsr.tsv", max_length=256)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("failed", "FAILED"), ("ingested", "INGESTED")],
                        default="ingested",
                        max_length=48,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dsrs",
                        to="dsrs.currency",
                    ),
                ),
            ],
            options={
                "db_table": "dsr",
            },
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                ("name", models.CharField(default="Spain", max_length=48, null=True)),
                (
                    "code_2",
                    models.CharField(
                        default="ES", max_length=2, primary_key=True, serialize=False
                    ),
                ),
                ("code_3", models.CharField(max_length=2, null=True)),
                (
                    "local_currency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territories",
                        to="dsrs.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "territory",
                "verbose_name_plural": "territories",
                "db_table": "territory",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dsp_id", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256, null=True)),
                ("artists", models.CharField(max_length=256, null=True)),
                ("isrc", models.CharField(max_length=256, null=True)),
                ("usages", models.IntegerField()),
                ("revenue", models.BigIntegerField()),
                (
                    "dsrs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource",
                        to="dsrs.dsr",
                    ),
                ),
            ],
            options={
                "db_table": "resource",
            },
        ),
        migrations.AddField(
            model_name="dsr",
            name="territory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dsrs",
                to="dsrs.territory",
            ),
        ),
    ]
